language: python
python:
    - 3.7

sudo: required

cache: pip
        
branches:
    - master

env:
    matrix:
        - PLATFORMIO_CI_SRC=examples/RawAmbientLight_Interrupt
        - PLATFORMIO_CI_SRC=examples/RawAmbientLight_OnDemand
        - PLATFORMIO_CI_SRC=examples/RawProximity_Interrupt
        - PLATFORMIO_CI_SRC=examples/RawProximity_OnDemand

install:
    - pip install -U platformio
    - platformio platform install -f infineonxmc 
    - platformio platform install -f atmelavr

script:
    - platformio ci --lib="." --board=xmc1100_xmc2go --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno 
